config/routes.rb
Wifiplatform::Application.routes.draw do
  get "/msignup" => "members#signup", :as => "msignup"
  get "/mlogin" => "members#login", :as=>"mlogin"
  delete "/:member_mac/logout" => "members#logout", :as => "mlogout" 
  post "/create_login_session" => "members#create_login_session"
  resources :members, only: [:create]

  root :to=>"about#main"
  match "login"=>"info#marketing",  :as=>"login"
  match "submit_login_form" => "user#login"
  get "/about/showdata" => "about#showdata"
  get "/week/data" => "weeks#data" 
  get "/test" => "portal#show", :as => "portal_other" 
  get "/rank" => "portal#rank"
  get "/hotmenu" => "portal#hotmenu"
  get "/:member_mac/portal" => "portal#portal", :as => "portal_main" 
  get "/hotapp" => "portal#hotapp"
  get "/about/message" => "about#message"
  get "/create_course" => "courses#new", :as=>"create_course"
  get "/logout"=>"user#logout", :as=>"logout"
  post "/course" => "courses#create"
  get "/course" => "courses#index", :as => "course_index" 
  get "/:member_name/:course_name/edit" => "courses#edit" , :as => "edit_course"
  delete "/:member_name/:course_name" => "courses#destroy"
  match '/update_poster/:course_id' => 'courses#update_poster', :as => :update_poster
  put '/course' => 'courses#update'
  
  get '/connect' => 'weibo#connect'
  get '/callback' => 'weibo#callback'
  get '/about/checkapi' => 'about#checkapi'
  get 'about/thirdparty' => 'about#thirdparty'
  post '/example' => 'about#example'
  post '/:member_mac/:app_name/open' => 'app#app_on'
  post '/:member_mac/:app_name/close' => 'app#app_off'
  post '/freeland'  =>"app#freeland"
  post '/wificon'  =>"app#wificon"
end

app/views/shared/_fileupload_widget.html.haml
- content_for :template_js do
  = javascript_include_tag 'i_fileupload'
  :javascript
    jQuery(function($) {
      var textarea = $("#{textarea_selector}");
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          dataType: 'json',
          url: '/blog_images.json',
          maxFileSize: 1024 * 1024 * 5,
          add: function(e, data){
            types = /(\.|\/)(gif|jpe?g|png)$/i;
            file = data.files[0];
            if (types.test(file.type) || types.test(file.name))
            {
              data.submit();
            }
            else
            {
              alert(file.name + " is not a image file");
            }
          },
          start: function(e) {
            _tip.html('图片上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                new_pic = "\n" + "![](" + file.url + ")";
                textarea.atCaret('insert', new_pic);
              });
          },
          always: function(e) {
            _tip.html("上传图片");
          },
      });
    });

.pull-right
  %a.fileupload-btn.action_label
    %span#upload-tip 上传图片
    %input#fileupload{:type => 'file', :multiple => true, :name => "blog_image[asset][]"}

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash-alert">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="flash-error">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      企业Wifi服务平台
    </a>
    <ul id="user-links">
      <% if current_user %>
        <li><%= link_to current_user.name %></li>
        <li><%= link_to "退出", mlogout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "注册", msignup_path %></li>
        <li><%= link_to "登录", mlogin_path %></li>
      <% end %>
    </ul>
  </div>  
</div>

app/views/shared/_header_logged_in.html.erb
<div class="header header-logged-in">
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      企业Wifi服务平台 
    </a>
    <ul id="user-links">
      <li class="name" > <%= current_user.mac %> </li>
      <li> <%= link_to t("logout"), logout_path %></li>
    </ul>
  </div>
</div>

app/views/shared/_header_logged_out.html.erb
<div class="header header-logged-out">
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      企业Wifi服务平台
    </a>

  </div>
</div>

app/views/shared/_home_login_form.erb
<%= form_tag "/submit_login_form", :class => "home-signup" do  %>
  <dl class="form">
    <dd>
    <%= text_field_tag :mac, params[:mac],  :placeholder => "mac", :class => "short" %>
    </dd>
  </dl>
  <p class="text-muted">登陆后就可定制你的广告了</p>
  <p><%= submit_tag "登陆", :class => "button button-block primary" %></p>
<% end %>

app/views/shared/_home_masthead.html.erb
<div class="masthead">
  <div class="container">
    <div class="home-signup">
      <%= render 'shared/home_login_form' %>
    </div>
    <%= render 'shared/tagline' %>
  </div>
</div>

app/views/shared/_home_signup_form.erb
<%= form_for(@user,:url => "/member", :class => "home-signup") do |f|  %>
  <dl class="form">
    <dd>
    <%= f.text_field :name, :placeholder => t('signup_username'), :class => "short" %>
    </dd>
  </dl>
  <p class="text-muted">注册后就可以关注你喜欢的课程了</p>
  <p><%= f.submit t("signup_free"), :class => "button button-block primary" %></p>
<% end %>

app/views/shared/_marketing.html.erb
<div class="container">

  <div class="marketing">

    <hr class="soften">

    <% if !@recent_courses.empty? %>
      <div class="courses clearfix">
        <% @recent_courses.each do |course| %>
          <div class="course">
            <%= render "courses/course", :course => course %>
          </div>
        <% end %>
      </div>
      <%= link_to "查看所有课程", course_index_path, class: "all-courses button" %>
    <% else %>
      <p>
      No Courses found
      </p>
    <% end %>
  </div>

</div>

app/views/shared/_member_list.html.erb
<ol class="member-list">
  <% members.each do |member| %>
    <li class="member-list-item">
      <%= link_to member_path(member.name) do %>
        <%= image_tag member.final_avatar_url, alt: "uprofile", :class => "gavatar" %>
      <% end %>
      <div class="member-list-container">
        <h3 class="member-name">
          <%= link_to member_path(member.name) do %>
            <%= member.name.truncate(16) %>
          <% end %>
        </h3>
        <p class="courses">courses: <%= member.courses.count %></p>
        <p class="comments">comments: <%= member.comments.count %></p>
        <p class="join-date">joined: <%= member.created_at.strftime("%Y-%m-%d") %></p>
      </div>
    </li>
  <% end %>
</ol>

app/views/shared/_tagline.html.erb
<div class="tagline">
  <h1 class="heading">定制你的路由器广告</h1>
  <div class="subheading">
    <p>
    简单几步发布广告，获得用户反馈，实现营销推广，为公司带来收益
    </p>
    <p>
    <a href="#">如何注册成为会员？</a>
    </p>
  </div>
</div>