config/routes.rb
Wifiplatform::Application.routes.draw do
  get "/msignup" => "members#signup", :as => "msignup"
  get "/mlogin" => "members#login", :as=>"mlogin"
  delete "/:member_mac/logout" => "members#logout", :as => "mlogout" 
  post "/create_login_session" => "members#create_login_session"
  resources :members, only: [:create]

  root :to=>"about#main"
  match "login"=>"info#marketing",  :as=>"login"
  match "submit_login_form" => "user#login"
  get "/about/showdata" => "about#showdata"
  get "/week/data" => "weeks#data" 
  get "/test" => "portal#show", :as => "portal_other" 
  get "/rank" => "portal#rank"
  get "/hotmenu" => "portal#hotmenu"
  get "/:member_mac/portal" => "portal#portal", :as => "portal_main" 
  get "/hotapp" => "portal#hotapp"
  get "/about/message" => "about#message"
  get "/create_course" => "courses#new", :as=>"create_course"
  get "/logout"=>"user#logout", :as=>"logout"
  post "/course" => "courses#create"
  get "/course" => "courses#index", :as => "course_index" 
  get "/:member_name/:course_name/edit" => "courses#edit" , :as => "edit_course"
  delete "/:member_name/:course_name" => "courses#destroy"
  match '/update_poster/:course_id' => 'courses#update_poster', :as => :update_poster
  put '/course' => 'courses#update'
  
  get '/connect' => 'weibo#connect'
  get '/callback' => 'weibo#callback'
  get '/about/checkapi' => 'about#checkapi'
  get 'about/thirdparty' => 'about#thirdparty'
  post '/example' => 'about#example'
  post '/:member_mac/:app_name/open' => 'app#app_on'
  post '/:member_mac/:app_name/close' => 'app#app_off'
  post '/freeland'  =>"app#freeland"
  post '/wificon'  =>"app#wificon"
end

app/controllers/about_controller.rb
# encoding: utf-8
class AboutController < ApplicationController
  def main
    if current_user
      @user = User.find_by_mac(current_user.mac) if current_user
      @courses = @user.courses
    else 
      redirect_to login_path
    end
  end
  def showdata
  end
  
  def checkapi
  end
  
  def checkapi1
  end
  def thirdparty
  end

  def message
    @message = Message.new(:user_id=>current_user.id) 
    @messages = Message.find_all_by_user_id(current_user.id)
  end
  
  def example
    message = Message.new(params[:message]);
    if message.save
      app_key = Settings.pushkey.app_key
      master_secret = Settings.pushkey.master_secret
      time_to_live = 60 * 60 * 24
      jpush_client = JPushApiRubyClient::Client.new(app_key, master_secret, 'platform' => JPushApiRubyClient::PlatformType::ANDROID);
      send_no = jpush_client.generate_send_no
      msg_title = params[:message][:title]
      msg_content = params[:message][:content]
      jpush_client.send_notification_with_appkey(send_no, msg_title, msg_content)
      redirect_to "/about/message", :notice=>"消息发送成功"
    else
      redirect_to "/about/message", :notice=>"消息发送失败"
    end
  end

end

app/views/about/_ad.html.erb
<%= image_tag course.poster_url, :id => 'adpost'%>

app/views/about/_add_form.html.erb
<%= form_for(@message, :url=>"/example")  do |f| %>

  <%= f.hidden_field :user_id %>
  <dl class="form">
    <dt> <%= f.label "消息标题" %> </dt>
    <dd> <%= f.text_field :title, :class => "short"  %> </dd>
  </dl>
  <dl class="form">
    <dt>
      <%= f.label "消息内容" %>
    </dt>
    <dd>
      <%= f.text_area :content, :size => "14x4" %>
    </dd>
  </dl>
  <br>
  <div>
    <%= submit_tag "群发消息", :class => "button primary" %>
    <span id="edit-course-delete">
      <%= link_to "返回", :root  %>
    </span>
  </div>
<% end %>

app/views/about/_aside.html.erb
<div class="menu-container">
  <ul class="menu">
    <li><a class="<%= request.path == "/"? "active main":"main" %>" href="/">广告管理</a></li>
    <li><a class="<%= request.path == "/about/showdata"? "active team":"team" %>" href="/about/showdata">数据统计</a></li>
    <li><a class="<%= request.path == "/about/message"? "active faq":"faq" %>" href="/about/message">消息群发</a></li>
    <li><a class="<%= request.path == "/about/thirdparty"? "active faq":"faq" %>" href="/about/thirdparty">客户端定制</a></li>
  </ul>
</div>
<div class="contact-us">
  <h3>找到我们</h3>
  <p>
    我们希望听到你的反馈，哪怕是一句早上好。给我们<a class="" href="mailto:huangzhe@ctbri.com.cn"><span><i class="icon-envelope"></i></span></a>吧。
  </p>
  <p>
    <span class="label label-info">
      <i class="icon-envelope"></i> Email
    </span>
    <br/>
    <a href="mailto:huangzhe@ctbri.com.cn">
      huangzhe@ctbri.com.cn
    </a>
  </p>
</div>

app/views/about/_trans.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "transtyle" %>
  <%= stylesheet_link_tag "trantab" %>
<% end  %>  
<div class="container1">
	<div id="row1">
		<div id="left">
		<table cellspacing="0" id="playlistTable" summary="">
			<caption>今日连入mac地址共 10 个</caption>

			<colgroup>
			<col id="PlaylistCol" />
			<col id="trackCol" />
			<col id="artistCol" />

			</colgroup>

			<thead>
			<tr>
			<th id="playlistPosHead" scope="col">Playlist Position</th>
			<th scope="col">MAC地址</th>
			<!-- <th scope="col">接入时长</th> -->

			</tr>
			</thead>

			<tbody>
			<tr class="odd">
			<td>1</td>
			<td>00:01:6C:06:A6:29 </td>
			

			</tr>

			<tr>
			<td>2</td>
			<td>00:05:5D:E8:0F:A3</td>
			

			</tr>

			<tr class="odd">
			<td>3</td>
			<td>64:B9:E8:F2:GE:12</td>
			

			</tr>

			<tr>
			<td>4</td>
			<td>12:EF:3U:AS:1N:SA</td>
			

			</tr>

			<tr class="odd">
			<td>5</td>
			<td>C3:3G:FO:WI:29:X8</td>
			

			</tr>

			<tr>
			<td>6</td>
			<td>C7:EH:7S:OG:2N:8F</td>
			

			</tr>

			<tr class="odd">
			<td>7</td>
			<td>S5:MB:9B:4F:3L:90</td>
			

			</tr>

			<tr>
			<td>8</td>
			<td>21:3D:F4:A3:23:FR</td>
			

			</tr>

			<tr class="odd">
			<td>9</td>
			<td>AE:3F:Q3:5J:AE:6K</td>
			

			</tr>

			<tr>
			<td>10</td>
			<td>9B:6K:PJ:5M:0B:KK</td>
			

			</tr>
			</tbody>
		</table>
	</div>

	<div id="tri"></div>

	<div id="mid">
		<div id="top">
			
				<p>其中访问APP商店数量
					<span>8</span>
				</p>
			
			<div class="cent"> 
				<p> 
					<div class="Bars"> 
    					<div style="width: 80%;"> 
        					<span>80%</span> 
    					</div> 
					</div> 
				</p> 
			</div> 
		</div>

		<div id="bot">
			<p><span>4人 （转化率50%）</span>继续进行了App下载</p>
		</div>
	</div>
	<div id="tri">
		
	</div>
	<div id="right">
		<table cellspacing="0" id="playlistTable" summary="">
			<caption>访问商店mac地址共 8 个</caption>

			<colgroup>
			<col id="PlaylistCol" />
			<col id="trackCol" />
			<col id="artistCol" />

			</colgroup>

			<thead>
			<tr>
			<th id="playlistPosHead" scope="col">Playlist Position</th>
			<th scope="col">MAC地址</th>
			<!-- <th scope="col">接入时长</th> -->

			</tr>
			</thead>

			<tbody>
			<tr class="odd">
			<td>1</td>
			<td>00:01:6C:06:A6:29 </td>
			

			</tr>

			<tr>
			<td>2</td>
			<td>00:05:5D:E8:0F:A3</td>
			

			</tr>

			<tr class="odd">
			<td>3</td>
			<td>64:B9:E8:F2:GE:12</td>
			

			</tr>

			<tr>
			<td>4</td>
			<td>12:EF:3U:AS:1N:SA</td>
			

			</tr>

			<tr class="odd">
			<td>5</td>
			<td>C3:3G:FO:WI:29:X8</td>
			

			</tr>

			<tr>
			<td>6</td>
			<td>C7:EH:7S:OG:2N:8F</td>
			

			</tr>

			<tr class="odd">
			<td>7</td>
			<td>S5:MB:9B:4F:3L:90</td>
			

			</tr>

			<tr>
			<td>8</td>
			<td>21:3D:F4:A3:23:FR</td>
			

			</tr>
			</tbody>
		</table>
	</div>
	</div>
<div class="clear1"></div>
	<div id="row2">
		   <div id="left">
		    <table cellspacing="0" id="playlistTable" summary="">
			<caption>进行下载的 4 个MAC地址</caption>

			<colgroup>
			<col id="PlaylistCol" />
			<col id="trackCol" />
			<col id="artistCol" />

			</colgroup>

			<thead>
			<tr>
			<th id="playlistPosHead" scope="col">Playlist Position</th>
			<th scope="col">MAC地址</th>
			<!-- <th scope="col">接入时长</th> -->

			</tr>
			</thead>

			<tbody>
			<tr class="odd">
			<td>1</td>
			<td>12-EF-3U-AS-1N-SA</td>
			

			</tr>

			<tr>
			<td>2</td>
			<td>C7-EH-7S-OG-2N-8F</td>
			

			</tr>

			<tr class="odd">
			<td>3</td>
			<td>21-3D-F4-A3-23-FR</td>
			

			</tr>

			<tr>
			<td>4</td>
			<td>9B-6K-PJ-5M-0B-KK</td>
		

			</tr>

			
			</tbody>
		</table>
	</div>

	<div id="tri"></div>

	<div id="mid">
		<div id="top">
			<div class="detail1">
				<p>被下载的APP应用<br />
					<span>3</span>
					（共10个应用）
				</p>
			</div>
			<div class="cent"> 
				<p> 
					<div class="Bars"> 
    					<div style="width: 30%;"> 
        					<span>30%</span> 
    					</div> 
					</div> 
				</p> 
			</div> 
		</div>
		<!-- <div id="bot">
			<p>转化率 50%</p>
		</div> -->
	</div>
	<div id="tri">
		
	</div>
	<div id="right">
		<table cellspacing="0" id="playlistTable" summary="">
			<caption>被下载的 3 个APP</caption>

			<colgroup>
			<col id="PlaylistCol" />
			<col id="trackCol" />
			<col id="artistCol" />

			</colgroup>

			<thead>
			<tr>
			<th id="playlistPosHead" scope="col">Playlist Position</th>
			<th scope="col">APP名称</th>
			<th scope="col">下载人数</th>

			</tr>
			</thead>

			<tbody>
			<tr class="odd">
			<td>1</td>
			<td>迅雷离线加速</td>
			<td>2</td>

			</tr>

			<tr>
			<td>2</td>
			<td>飞机大战</td>
			<td>1</td>

			</tr>

			<tr class="odd">
			<td>3</td>
			<td>优惠卷</td>
			<td>1</td>

			</tr>
			</tbody>
		</table>
	</div>
	</div>

</div>

app/views/about/_trans1.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "nv.d3" %>
<% end  %>  
<% content_for :template_js do %>
  <%= javascript_include_tag 'd3.v3.min'%> 
  <%= javascript_include_tag 'nv.d3'%>
  <script>
d3.json("/jqm/img/daytrend.json", function(data) {
  	 nv.addGraph(function() {
    var chart =
     nv.models.multiBarChart()
      .transitionDuration(350)
       .x(function(d) { return d[0] })   
       .y(function(d) { return d[1] })  
      .reduceXTicks(false)
      .rotateLabels(0)     
      .showControls(true)  
      .groupSpacing(0.1);

    chart.xAxis
        .tickFormat(d3.format(',f'));

    chart.yAxis
        .tickFormat(d3.format('.f'));

    d3.select('#chart1 svg')
        .datum(data)
        .call(chart);

    nv.utils.windowResize(chart.update);
	
    return chart;
	
})
});
  </script>
<% end %>
<div class="container1">
<div id='chart1'>
  <svg style='height:500px'> </svg>
</div>
</div>

app/views/about/checkapi.html.erb
<% content_for :template_js do %>
<script>
  jQuery(function($) {
      $( "#weiboon" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/weibo/open"})
      });
      $( "#weibooff" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/weibo/close"})
      });
      $( "#gameon" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/game/open"})
      });
      $( "#gameoff" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/game/close"})
      });
      $( "#menuon" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/menu/open"})
      });
      $( "#menuoff" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/menu/close"})
      });
      $( "#groupon" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/group/open"})
      });
      $( "#groupoff" ).click(function() {
        $.ajax({type:"POST",url:"/11:22:33:44:55:66/group/close"})
      });
  });
</script>
<% end %>
<div class="about-content">
  <h2>应用商店</h2>
  <hr>
  <center>
    <div class="courses" >
      <div class ="course">
        <div class="course-thumb">
          <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="../../../uploads/poster/gift.png" >
          <div class="caption">
            <h3>优惠券</h3>
            <p>访客通过微博账号登陆，获取优惠券.</p>
            <p><a href="#"  id="weiboon" class="btn btn-primary">开启</a> <a href="#" id="weibooff" class="btn">关闭</a></p>
          </div>
        </div>  
      </div>

      <div class ="course">
        <div class="course-thumb">
          <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="../../../uploads/poster/game.png" >
          <div class="caption">
            <h3>餐前游戏</h3>
            <p>为等位访客提供小游戏.</p>
            <p><a href="#" id="gameon" class="btn btn-primary">启动</a> <a href="#" id="gameoff" class="btn">关闭</a></p>
          </div>
        </div>  
      </div>
    </div>
    <br>
    <div class="courses" >
      <div class ="course">
        <div class="course-thumb">
          <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="../../../uploads/poster/speedup.png" >
          <div class="caption">
            <h3>访问加速</h3>
            <p>App Store/Google访问加速.</p>
            <p><a href="#" id="groupon"  class="btn btn-primary">开启</a> <a href="#" id="groupoff" class="btn">关闭</a></p>
          </div>
        </div>  
      </div>

      <div class ="course">
        <div class="course-thumb">
          <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="../../../uploads/poster/appstore.png" >
          <div class="caption">
            <h3>应用中心</h3>
            <p>提供应用推荐安装服务</p>
            <p><a href="#" id="menuon"  class="btn btn-primary">启动</a> <a href="#" id="menuoff"  class="btn">关闭</a></p>
          </div>
        </div>  
      </div>
    </div>
  </center> 
</div>

app/views/about/checkapi1.html.erb
<% content_for :template_js do %>
  <%= javascript_include_tag 'bootstrap.min'%>
<% end %>
<div class="about-team">
  <h2>行业应用</h2>
  <hr>
  <br/>

  <ul class="thumbnails">
    <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail label</h3>
      <p>Thumbnail caption...</p>
    </div>
    </li>
  </ul>

  <ul class="thumbnails">
    <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail label</h3>
      <p>Thumbnail caption...</p>
    </div>
    </li>
  </ul>

  <ul class="thumbnails">
    <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail label</h3>
      <p>Thumbnail caption...</p>
    </div>
    </li>
  </ul>

  <ul class="thumbnails">
    <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail label</h3>
      <p>Thumbnail caption...</p>
    </div>
    </li>
  </ul>
</div>

app/views/about/main.html.erb
<div class="owned-course-section clearfix">
  <div class="user-course-header">
    <% if current_user == @user %>
      <%= link_to create_course_path, :class => "button primary new-course" do %>
        创建广告
        <i class='icon-hand-right icon-large'></i>
      <% end %>
    <% end %>
    <h2>我的广告:</h2>
  </div>
  <% if @courses.present? %>
    <div class="courses">
      <% @courses.each do |course| %>
        <div class="course">
          <%= render "courses/ad", :course => course %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>无任何广告</p>
  <% end %>
</div>

app/views/about/message.html.erb
<div class="about-team">
  <h2>消息群发</h2>
  <hr>

  <%= render 'add_form', :message => @message  %>
</div>
<hr>
<br>
<h2>群发记录</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>消息标题</th>
      <th>发送时间</th>
      <th>消息状态</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each_with_index do |msg,index| %>
    <tr>
      <td><%= index %></td>
      <td><%= msg.title %></td>
      <td><%= msg.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td>发送成功</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/about/showdata.html.erb
<% content_for :template_js do %>
  <%= javascript_include_tag 'hierarchical-pie'%> 
  <%= javascript_include_tag 'mustache'%>
  <script>
    jQuery(function($) {
      var holder = $('#pie-demo1');
      holder.empty();

      $.getJSON('/week/data.json', function(data) {
        new HierarchicalPie({
          chartId : '#pie-demo-1',
          data : data,
          legendContainer : '#pie-chart-legend-1',
          navigation      : '#chart-navigator-1'
        });
      });
    });
  </script>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "piestyle" %>
<% end  %>  
<div class="about-content">
  <h2>每周/日消费分析饼图</h2>
  <hr>
  <div class="product3-zone">
  <div class="product-info-left3">
  <br>
  <div class="chart-navigator clearfix" id="chart-navigator-1" >
    <a href="#" class="btn btn-primary" id="btnRoot" title="Go back to root" rel="tooltip">返回</a>
  </div>

  <div id="pie-demo-1" style="width: 400px;" ></div>
  </div>
  <div class="products-info-right3" >
  <div id="pie-chart-legend-1" >
    <table class="table table-condensed table-legend">
      <thead>
        <tr>
          <th></th>
          <th>星期</th>
          <th>连接总人数</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
    <hr>
    <% content_for :template_js do %>
      <script id="rowTemplate" type="text/template">
        <td class="color-cell">
          <span class="cat-color" style="background: {{color}};"></span>
        </td>
        <td>
          {{#isDirect}}
          <span title="Directly in this category" rel="tooltip"><i class="icon-info"></i></span>
          {{/isDirect}}
          {{category}}
        </td>
        <td class="cost">{{cost}}</td>
      </script>
    <% end %>
  </div>
  </div>
  <h2>三天内各时段访客数据统计</h2>
  <hr/>

</div>
<%= render "trans1"  %>

app/views/about/thirdparty.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "tinygame" %>
<% end  %>  
<div class='container'>
  <br />
  <hr/>
  <br />
<div class="product1-zone">
  <div class="products-img-left">
          <img src="../../../uploads/poster/gameadv1.png" >
          <br />        
  </div >
  <div class="products-info-right center">
    <div class="product-title">定制您的客户端</div>
    <div class="product-content">
      <p>启动客户端时加入企业广告</p>
      <p>定期推送广告</p>
      <p>结合游戏插入广告</p>
    </div>
  </div>
</div>
<hr>

<div class="product-zone">
  <div class="product-info-left">
    <div class="product-title">游戏积分榜</div>
    <div class="product-content">
      <p>建立商家与客户的互动关系</p>
      <p>打发顾客等位与等菜时间</p>
      <p>打飞机，切水果，游戏简单易操作</p>
    </div>
  </div>
  <div class="products-info-right2">
    <table class="table">
      <thead>
        <tr>
          <th>排名</th>
          <th>姓名</th>
          <th>积分</th>
          <th>获奖日期</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Mark</td>
          <td>999999</td>
          <td>2013-12-1</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Jacob</td>
          <td>888888</td>
          <td>2013-12-12</td>
        </tr>
        <tr>
          <td>3</td>
          <td>Larry</td>
          <td>777777</td>
          <td>2013-12-23</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

</div>